### ISSUE TITLE
IMPORTANT: Do not bump version before mv4 stable release

### ISSUE THREAD

**Issue by Torrekie** [bouldev/PhoenixBuilder#6]
As of Sun Jul 14 15:07:31 UTC 2024, we stopped providing `api.fastbuilder.pro` by 744dbf64439e96574258119906fa6dd2171e84c2, please do not perform version bump before we take any further operations.

**Comment by Happy2018new** [comment]
The signature feature of BDX is still exist, so I planned to remove them tomorrow.

**Comment by Torrekie** [comment]
now we are ready to bump

**Comment by Happy2018new** [comment]
> now we are ready to bump

#4 is not complete, so the action will failed when build release...

**Comment by Happy2018new** [comment]
请允许我再次重新禁用存在问题的构建以提升版本。

**Comment by Happy2018new** [comment]
经过之前的测试，**PhoenixBuilder** 新验证服务器可以如期对接当前的 **PhoenixBuilder**，所有本议题标记为 **已完成** 。
